class _BotCommands:
    def __init__(self):
        self.StartCommand = 'mulai'
        self.MirrorCommand = 'cermin'
        self.UnzipMirrorCommand = 'cerminunzip'
        self.TarMirrorCommand = 'cermintar'
        self.ZipMirrorCommand = 'cerminzip'
        self.CancelMirror = 'batal'
        self.CancelAllCommand = 'batalkan'
        self.ListCommand = 'daftar'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'pengguna'
        self.AuthorizeCommand = 'mengizinkan'
        self.UnAuthorizeCommand = 'tidaksah'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'reboot'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'tolong'
        self.LogCommand = 'log'
        self.SpeedCommand = 'aducepat'
        self.CloneCommand = 'ganda'
        self.CountCommand = 'hitung'
        self.WatchCommand = 'nonton'
        self.TarWatchCommand = 'nontontar'
        self.DeleteCommand = 'hapus'
        self.UsageCommand = 'sisakuota'
        self.MediaInfoCommand = 'mediainfo'
        self.ShellCommand = 'cmd'
        self.ExecHelpCommand = 'tolongexec'


BotCommands = _BotCommands()
