class _BotCommands:
    def __init__(self):
        self.StartCommand = 'mulai'
        self.MirrorCommand = 'cermin'
        self.UnzipMirrorCommand = 'unzipmirrorX'
        self.TarMirrorCommand = 'tarmirrorX'
        self.CancelMirror = 'batal'
        self.CancelAllCommand = 'cancelallX'
        self.ListCommand = 'daftar'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'usersX'
        self.AuthorizeCommand = 'authorizeX'
        self.UnAuthorizeCommand = 'unauthorizeX'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'pingX'
        self.RestartCommand = 'reboot'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'bantuan'
        self.LogCommand = 'logX'
        self.SpeedCommand = 'speedtestX'
        self.CloneCommand = 'ganda'
        self.CountCommand = 'hitung'
        self.WatchCommand = 'nontom'
        self.TarWatchCommand = 'nontontar'
        self.DeleteCommand = 'hapus'
        self.UsageCommand = 'usageX'
        self.MediaInfoCommand = 'mediainfoX'
        self.ConfigMenuCommand = 'configX'
        self.ShellCommand = 'cmd'
        self.UpdateCommand = 'perbarui'

BotCommands = _BotCommands()
